noortdd/urls.py
from django.urls import re_path
from django.urls import path
from .views import index,save_status,register_profile, save_profile, clear_status, profil, books, get_books, search_books, register_ajax, register_ajax_create, check_mail, oauth

urlpatterns = [
	path('',index, name='index'),
	path('save_status/',save_status,name='save_status'),
	path('register/',register_profile,name='register_profile'),
	path('save_profile/', save_profile, name='save_profile'),
	path('clear_status/', clear_status, name='clear_status'),

	# story 8
	path('profil/',profil,name='profil'),
	
	# story 9
	path('books/', books, name='books'),
	path('get_books/', get_books, name='get_books'),
	path('search_books/', search_books, name='get_books'),

	# story 10
	path('register_ajax/', register_ajax, name='register_ajax'),
	path('register_ajax/create/', register_ajax_create, name='register_ajax_create'),
	path('register_ajax/checkmail/', check_mail, name='check_mail'),

	# story 11
	path('oauth/', oauth, name='oauth'),

]

story6/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('noortdd.urls', 'noortdd'), namespace='noortdd')),

]

noortdd/models.py
from django.db import models
from django.utils import timezone
# from .forms import Status_Form

# Create your models here.
class Status(models.Model):
	date = models.DateTimeField(default=timezone.now())
	status = models.CharField(max_length=300)

class Profile(models.Model):
	
	name = models.CharField(max_length=30)
	dob = models.DateField(default='')
	npm = models.CharField(max_length=10)

class Register(models.Model):
	name = models.CharField(max_length=100)
	email = models.CharField(max_length=100, unique = True)
	password = models.CharField(max_length=20)

noortdd/forms.py
from django import forms
#from .models import Status

class Status_Form(forms.Form):
	error_messages = {
		'required': 'Please type',
	}

	status_attrs = {
		'type': 'text',
		'class': 'todo-form-input',
		'placeholder': 'status',
		'id': 'statusid'
	}


	status = forms.CharField(label='Status', required=True, max_length=67, widget=forms.TextInput(attrs=status_attrs))

class Profile_Form(forms.Form):
	error_messages = {
		'required': 'Please type',
	}

	char_attrs = {
		'class': 'form-control',
	}

	num_attrs = {
		'class': 'form-control',
		'type': 'number',
	}

	date_attrs = {
		'class': 'form-control',
		'type': 'date',
	}

	name = forms.CharField(label='Name', required=True, max_length=30, widget=forms.TextInput(attrs=char_attrs))
	dob = forms.CharField(label='Date of Birth', required=True, widget=forms.DateInput(attrs=date_attrs))
	npm = forms.CharField(label='NPM', required=True, max_length=10, widget=forms.TextInput(attrs=num_attrs))

class Register_Ajax(forms.Form):
	error_messages = {
		'required': 'Please type',
	}

	text_attrs = {
		'class': 'form-control',
	}

	num_attrs = {
		'class': 'form-control',
		'type': 'number',
	}

	name = forms.CharField(label='Name', required=True, widget=forms.TextInput(attrs=text_attrs))
	email = forms.CharField(label='Email', required=True, widget=forms.EmailInput(attrs=text_attrs))
	password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput(attrs=text_attrs))

noortdd/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Status, Profile, Register
from .forms import Status_Form, Profile_Form, Register_Ajax
import json
import requests

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

response = {}

# Create your views here.
def index(request):
	all_status = Status.objects.all()
	response['all_status'] = all_status
	response['title'] = 'Add Status'
	response['add_status'] =  Status_Form()
	return render(request,'landing_page.html',response)

def save_status(request):
	form = Status_Form(request.POST or None)
	if(request.method=='POST' and form.is_valid()):
		response['status']= request.POST['status']
		The_Status= Status(
			status=response['status'],
		  
		)
		The_Status.save()

	return HttpResponseRedirect('/')

	
def register_profile(request):
	all_profile = Profile.objects.all()
	response['all_profile'] = all_profile
	response['title'] = 'Add Profile'
	response['add_profile'] =  Profile_Form()
	return render(request,'register_profile.html',response)

def save_profile(request):
	form = Profile_Form(request.POST or None)
	if(request.method=='POST' and form.is_valid()):
		response['name']= request.POST['name']
		response['dob']= request.POST['dob']
		response['npm']= request.POST['npm']
		The_Profile= Profile(
			name=response['name'],
			dob=response['dob'],
			npm=response['npm'],
		)
		The_Status.save()

	return HttpResponseRedirect('/profile/')

def clear_status(response):
	Status.objects.all().delete()
	return HttpResponseRedirect('/')


# story 8
def profil(request):
	return render(request,'profil.html')


# story 9
def books(request):
	return render(request, 'books.html')

def get_books(request):
	print('test masuk')
	url = 'https://www.googleapis.com/books/v1/volumes?q=quilting'
	book = requests.get(url).json()
	return JsonResponse(book)

def search_books(request):
	print('masuk search')
	print(request)
	#temp = request.objects.get(data)
	temp = request.GET.get('inputStr','')

	print('temp pertama ' + temp)
	temp = 'https://www.googleapis.com/books/v1/volumes?q=' + temp
	
	print('temp kedua ' + temp)
	book = requests.get(temp).json()
	return JsonResponse(book)

# stoyy 10
def register_ajax(request):
	return render(request, 'register_ajax.html', {'Form' : Register_Ajax})


def register_ajax_create(request):
	try:
		if request.method == 'POST':
			name = request.POST['name']
			email = request.POST['email']
			password = request.POST['password']

			Register.objects.create(
				name = name,
				email = email,
				password = password
			)
		return HttpResponse('SUCCESS')

	except Exception as e:
		return HttpResponse('FAIL')


def check_mail(request):
	print(request)
	temp = request.GET['email']
	subscriber = Register.objects.all()
	print(subscriber)
	for data in subscriber:
		if(temp == data.email):
			return HttpResponse("")
	return HttpResponse("OK")

# story 11
def oauth(request):
	return render(request, 'oauth.html')
	
def register_user(request):
	name = request.POST['name']
	email = request.POST['email']
	password = request.POST['password']

	user = User.objects.create_user(name, email, password)

	return HttpResponse('')

def log_in(request):
	name = request.POST['name']
	password = request.POST['password']
	user = authenticate(request, username=username, password=password)

	if user is not None:
		login(request, user)
		return HttpResponse('Logged in')

	else:
		return HttpResponse('No ID found')


def log_out(request):
	logout(request)
	return HttpResponse('Logged out')

noortdd/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="google-signin-client_id" content="502256575677-uv3u46o2a7qut2gcb9qktl4a322ceoe8.apps.googleusercontent.com">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- load css -->
  <link rel="stylesheet" type="text/css" href="{% static 'maincss.css' %}">

  <!-- load js from external sources -->
  <!-- load cdn yg dari google-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

  <!-- ini untuk styling accordionnya -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  
  
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  
  <!-- script yang dipakai untuk accordionnya -->
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- load js -->
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/register.js' %}"></script>
  <script src="{% static 'js/books.js' %}"></script>


  


  
  <style>
  .loader {
    position: absolute;
      left: 50%;
      top: 50%;
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    width: 120px;
    height: 120px;
    -webkit-animation: spin 1s linear infinite;
    /* Safari */
    animation: spin 1s linear infinite;
  }

  /* Safari */
  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  </style>

  <title>NOOR</title>
</head>


<!--body id="change_this" onload="setTimeout(showPage, 1000);"-->
<body id="change_this">
<!-- ini loader -->
<!--div id="loader"></div-->

<div id="mainid">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='navbarid'>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" id='homebtn' href="{% url 'noortdd:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='regprofilebtn' href="{% url 'noortdd:register_profile' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:profil' %}">Profil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:books' %}">Books (Story 9)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:register_ajax' %}">Register (Story 10)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:oauth' %}">OAuth (Story 11)</a>
        </li>
      </ul>
    </div>
</nav>

<div class="container" id="main_container" style="background-color:;">

{% block content%} {% endblock %}

</div>
</div>

</body>
</html>

noortdd/templates/books.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div style="margin-left: auto; margin-right: auto; margin-top: 10px">
		<h1>AYY LMAO</h1>
	</div>
</div>
<div class="row" style="margin-bottom: 10px">
	<button type="button" class="btn btn-primary" id="get_books_btn" style="margin-left: auto; margin-right: auto;">GENERATE BOOKS</button>
</div>

<div class="row">
	<h3 id="books_header" style="margin-left: auto; margin-right: auto; display: block">Nothing to see here</h3>
	<div class="loader" id="loader" style="display: none"></div>

	<div id='books_menu' style="display: none">
		<div class="row" id="search_bar">
			<form onsubmit="return false;">
				<input id="search_box" type="text" placeholder="Search books">
				<button onclick="findBooks()"><i class="fa fa-search"></i></button>
			</form>
		</div>



		<div class="row">
			<h3>Jumlah buku favorit: </h3><h3 id="fav">0</h3>
		</div>
		<div class="loader" id="loader_books_search" style="display: none"></div>
		<div class="row">
		<div class="table-responsive">
		<table class="table" id="books_table">
			<thead>
				<th scope="col">No.</th>
				<th scope="col">Books</th>
				<th scope="col">Description</th>
				<th scope="col">Cover</th>
				<th scope="col">Favourite</th>
			</thead>
			<tbody id="lists">
				
			</tbody>
		</table>
		</div>
		</div>
	</div>
</div>

{% endblock %}

noortdd/templates/landing_page.html
{% extends 'base.html' %}

{% block content %}
<div class = "row">
	<h1 id='introid'>Hello, Apa kabar?</h1>
	<br>
	<br>
</div>
<div class="row">
	<form method="POST" action="{% url 'noortdd:save_status' %}">
		{% csrf_token %}
		{{ add_status.as_p }}
		<input id='submitid' type="submit" value="Submit">
	</form>
</div>

<div class="row">
	<div class="table-responsive">
		<table class="table">
			<thead>
				<th class="col-sm-6">Status</th>
				<th class="col-sm"> Time Published </th>
			</thead>
			<tbody>
				{% for data in all_status %}
				<tr>
					<td>{{ data.status }}</td>
					<td>{{ data.date }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock %}

noortdd/templates/oauth.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-1-sm">
    <div id="log-block" style="margin-top: 10px">
      <div class="g-signin2" data-onsuccess="onSignIn"></div>
    </div>
  </div>

  <div class="col-8-sm" style="margin-left: 20px">
    <p>test</p>
  </div>
</div>

<script src="https://apis.google.com/js/platform.js" async defer></script>

<script>
function onSignIn(googleUser) {
  var profile = googleUser.getBasicProfile();
  console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
  console.log('Name: ' + profile.getName());
  console.log('Image URL: ' + profile.getImageUrl());
  console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.

  var block = "<h3>"+profile.getName()+"</h3>"+"<img src='"+profile.getImageUrl()+"'>"+"<a href='#' onclick='signOut();'>Sign out</a>";

  $('#log-block').html(block);

}
</script>

<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      
      console.log('User signed out.');
    });
    var block = '<div class="g-signin2" data-onsuccess="onSignIn"></div>';
    $('#log-block').html(block);
  }
</script>

{% endblock %}

noortdd/templates/profil.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<!-- load css -->
	<link rel="stylesheet" type="text/css" href="{% static 'maincss.css' %}">

	<!-- load js from external sources -->
	<!-- load cdn yg dari google-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

	<!-- ini untuk styling accordionnya -->
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	
	
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	
	<!-- script yang dipakai untuk accordionnya -->
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

	<!-- load js -->
	<script src="{% static 'js/main.js' %}"></script>

	
	<style>
	#loader {
		position: absolute;
  		left: 50%;
  		top: 50%;
		border: 16px solid #f3f3f3;
		border-radius: 50%;
		border-top: 16px solid #3498db;
		width: 120px;
		height: 120px;
		-webkit-animation: spin 1s linear infinite;
		/* Safari */
		animation: spin 1s linear infinite;
	}

	/* Safari */
	@-webkit-keyframes spin {
		0% { -webkit-transform: rotate(0deg); }
		100% { -webkit-transform: rotate(360deg); }
	}

	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}
	</style>

	<title>Ayy lmao</title>
</head>
<body id="change_this" onload="setTimeout(showPage, 1000);">
<!-- ini loader -->
<div id="loader"></div>

<div id="main_id" style="display: none">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='navbarid'>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" id='homebtn' href="{% url 'noortdd:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='regprofilebtn' href="{% url 'noortdd:register_profile' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:profil' %}">Profil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:books' %}">Books (Story 9)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id='profilbtn' href="{% url 'noortdd:register_ajax' %}">Register (Story 10)</a>
        </li>
      </ul>
    </div>
</nav>

<div class="container" id="main_container" style="background-color:;">
	<div class="row" style="margin-top: 10px; margin-bottom: 30px;">
		<div class="col-sm-3">
			<img src="{% static 'meme.jpg' %}" class="image-fluid" style="max-width: 500px; width: 90%">
		</div>

		<div class="col-sm">
			<div class="row">
				<h1 id="head1" style="color:;">[INSERT H1 TEXT]</h1>
			</div>
			<div class="row">
				<h2 id="head2" style="color:;">[INSERT H2 TEXT]</h2>
			</div>
			<div class="row">
				<button type="button" class="btn btn-info" id="info" onclick="change_theme()">Ubah Tema!</button>
			</div>
		</div>
	</div>
	<div class="row" style="margin-top: 10px">
		<div class="col-sm-12">
			<div id="accordion" style="width: 80%">
				<h3>Aktifitas saat ini</h3>
				<div>
					<p>Membuat hal-hal ini berfungsi.</p>
					<p>Kedinginan di lab.</p>
				</div>

				<h3>Pengalaman organisasi/kepanitiaan</h3>
				<div>
					<p>Pernah main harvest moon (yg a wonderful life tapi).</p>
					<br>
					<p>Kalo yang serius sih baru staff IGI Compfest X</p>
				</div>

				<h3>Prestasi</h3>
				<div>
					<p>Pernah menang lomba berenang sblm lahir.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style="margin-left: 1%">
		<p style="font-size: 5px">Perasaan accordionnya udah bener malah jadi cuma bisa nampilin 1 line per extend dan harus discroll :/</p>
	</div>
</div>
</div>

<script>

</script>

</body>
</html>

noortdd/templates/register_ajax.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-1-sm">
    <form id="form" method="POST" onsubmit="return false;">
      {% csrf_token %}
      {{ Form }}
      <button type="submit" class="btn btn-success" id="submit_btn">Subscribe</button>
    </form>
  </div>
  <div class="col-8-sm" style="margin-left: 20px">
    <p>test</p>
  </div>
</div>
{% endblock %}

noortdd/templates/register_profile.html
{% extends 'base.html' %}

{% block content %}
<div class = "row">
	<h1>Hello! Salam kenal</h1>
	<br>
	<br>
</div>
<div class="row">
	<form method="POST" action="{% url 'noortdd:save_profile' %}">
		{% csrf_token %}
		{{ add_profile.as_p }}
		<input  type="submit" value="Submit">
	</form>
</div>

{% endblock %}